-- Article comments. Mirrors the conventions of the other wc_* tables.
-- Run once against the production PostgreSQL database.

CREATE TABLE wc_comment (
	id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	unique_id         UUID NOT NULL,
	creation_date     TIMESTAMP NOT NULL,
	modification_date TIMESTAMP NOT NULL,
	article_id        INTEGER NOT NULL REFERENCES wc_article (id) ON DELETE CASCADE,
	name              VARCHAR(1024) NOT NULL,
	content           TEXT NOT NULL,
	date_time         TIMESTAMP NOT NULL
);

CREATE INDEX wc_comment_article_id_idx ON wc_comment (article_id);
